server:
  port: 8774

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}

spring:
  profiles:
    active: dev #开发环境
  application:
    name: channel-wechat
  cloud:
     client:
        ipAddress: 127.0.0.1          #服务消费者ip地址 
  # 格式化时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 消息队列
  rabbitmq:
    addresses: 192.168.10.21:5672,192.168.10.22:5672,192.168.10.23:5672
    username: admin
    password: admin
    virtual-host: /
    #addresses: 127.0.0.1:5672

#日志输出配置
logging:
  level:
    root: INFO
    com.itmuch: INFO
    org.springframework: INFO

#熔断器启动时间为 5 秒 ,默认是1秒
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 5000
              #ribbon请求连接的超时时间
ribbon:
  ConnectTimeout: 12000
  #请求处理的超时时间
  ReadTimeout: 12000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #对下个实例的重试次数
  MaxAutoRetriesNextServer: 1
  
pay:
  #cert: E:\dev\code\openapi-v2\wuzhenpay\channel-wechat\src\main\resources\cert\cert\
  cert: E:\workspace\openapi-v2\wuzhenpay\channel-wechat\src\main\resources\cert\
