server:
  port: 8086
  max-http-header-size: 5242880

spring:
  application:
    name: gateway-cms
  cloud:
     client:
        ipAddress: 127.0.0.1          #服务消费者ip地址
  # 格式化时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  zipkin:
    base-url: http://127.0.0.1:9211
    #redis缓存 单机版
  redis:
    host: 192.168.10.87
    port: 6379
    maxTotal: 200
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: 10000
    timeout: 10000

zuul:
  routes:
    service-merchant:
      path: /cms/**
      serviceId: service-cms
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}
feign:
  hystrix:
    enabled: true
#断路器的超时时间,断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
#熔断器启动时间为 30 秒 ,默认是1 秒
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 30000
#ribbon请求连接的超时时间
ribbon:
  ConnectTimeout: 10000
  #请求处理的超时时间
  ReadTimeout: 10000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #对下个实例的重试次数
  MaxAutoRetriesNextServer: 1