server:
  port: 8087
  
spring:
  application:
    name: gateway-pay
  cloud:
     client:
        ipAddress: 127.0.0.1          #服务消费者ip地址
  # 格式化时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  zipkin:
    base-url: http://127.0.0.1:9211
  datasource:
    name: test
    url: jdbc:mysql://rm-bp1ac3sqql7dt8w34o.mysql.rds.aliyuncs.com:3306/db_wuzhenpay?useUnicode=true&characterEncoding=UTF-8
    username: wuzhenpay
    password: A5tRqvnVEUbdwSHnG@
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #redis缓存 单机版
  redis:
    host: 192.168.10.87
    port: 6379
    maxTotal: 200
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: 10000
    timeout: 10000

zuul:
  routes:
    service-merchant:
      path: /merchant/**
      serviceId: service-merchant
    service-app:
      path: /app/**
      serviceId: service-app
      sensitive-headers: Cookie,Set-Cookie
    service-report:
      path: /report/**
      serviceId: service-report
    servcie-mbs:
      path: /mbs/**
      serviceId: service-mbs

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}
feign:
  hystrix:
    enabled: true
#断路器的超时时间,断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
#熔断器启动时间为 15 秒 ,默认是1 秒
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 15000
#ribbon请求连接的超时时间
ribbon:
  ConnectTimeout: 12000
  #请求处理的超时时间
  ReadTimeout: 12000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #对下个实例的重试次数
  MaxAutoRetriesNextServer: 1