server:
  port: 8088
zuul:
  routes:
    service-trade:
      path: /trade/**
      serviceId: service-trade
    channel-wechat:
      path: /notify/wechat
      serviceId:  channel-wechat
    channel-liantuo:
      path: /notify/liantuo
      serviceId:  channel-liantuo
    channel-mybank:
      path: /notify/mybank
      serviceId:  channel-mybank
    channel-hzceb:
      path: /notify/hzceb
      serviceId:  channel-hzceb
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}
feign:
  hystrix:
    enabled: true

spring:
  application:
    name: gateway-pay
  cloud:
     client:
        ipAddress: 127.0.0.1          #服务消费者ip地址
  # 格式化时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  zipkin:
    base-url: http://127.0.0.1:9211
#断路器的超时时间,断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
#熔断器启动时间为 15 秒 ,默认是1 秒
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 15000
#ribbon请求连接的超时时间
ribbon:
  ConnectTimeout: 12000
  #请求处理的超时时间
  ReadTimeout: 12000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #对下个实例的重试次数
  MaxAutoRetriesNextServer: 1