JAVA_LOGS: xxl-job

server:
  port: 8781
spring:
  profiles:
    active: dev #开发环境
  application:
    name: service-trade
  cloud:
     client:
        ipAddress: 127.0.0.1          #服务消费者ip地址
  datasource:
      name: test
      url: jdbc:mysql://rm-bp1ac3sqql7dt8w34o.mysql.rds.aliyuncs.com:3306/db_wuzhenpay??useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: wuzhenpay
      password: A5tRqvnVEUbdwSHnG@
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  # 格式化时间
  jackson:
     date-format: yyyy-MM-dd HH:mm:ss
     time-zone: GMT+8
  # 消息队列
  rabbitmq:
      addresses: 192.168.10.21:5672,192.168.10.22:5672,192.168.10.23:5672
      username: admin
      password: admin
      virtual-host: /
      #addresses: 127.0.0.1:5672
  #redis缓存 单机版
  redis:
      host: 192.168.10.87
      #cluster:
      #nodes: 192.168.10.31:6379,192.168.10.31:6380,192.168.10.32:6379,192.168.10.32:6380,192.168.10.33:6379,192.168.10.33:6380
      port: 6379
      maxTotal: 200
      pool:
          max-active: 8
          min-idle: 0
          max-idle: 8
          max-wait: 10000
      timeout: 10000
      #password: stevexu
mybatis:
    mapper-locations: classpath:mybatis/mappers/*.xml
    type-aliases-package: com.wuzhenpay.service.merchant.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#日志输出配置
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    com.itmuch: INFO
    org.springframework: INFO
    com.wuzhenpay.service.trade.feign: DEBUG
    com.wuzhenpay.service.trade.mapper: DEBUG
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/        #注册中心服务地址
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}
feign:
  hystrix:
    enabled: true
    
#熔断器启动时间为 15 秒 ,默认是1秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

ribbon:
  ConnectTimeout: 12000
  #请求处理的超时时间
  ReadTimeout: 12000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #对下个实例的重试次数
  MaxAutoRetriesNextServer: 1

#自定义参数
custom:
  notify:
    # 异步通知地址 http://openapi-local-dev.wuzhenpay.com
    url: http://openapitest.vipgz1.idcfengye.com
  jspay:
    # jspay页面地址
    url: http://192.168.10.127:8781/jspay/
  aes:
    # AES加密key
    key: 7C8794507CE27E7F765B44286B529A9C

xxl:
  job:
    admin:

      addresses: http://192.168.10.48:8080/xxl-job-admin
    executor:
      appname: wuzhenpay-service-trade
      ip:
      port: 9999
      logpath: ${JAVA_LOGS}/xxl-job
      logretentiondays: -1
    #accessToken: 32c3620bee0b59481e581c05eaa758a2
